---
flathub:
  system_packages:
    # Tools
    - com.mattjakeman.ExtensionManager
    - ca.desrt.dconf-editor
    - com.github.tchx84.Flatseal
    - org.gnome.seahorse.Application

  user_packages:
    # Chat
    - com.discordapp.Discord

    # Personal
    - org.keepassxc.KeePassXC
    - md.obsidian.Obsidian

    # Gaming
    - com.valvesoftware.Steam
    - com.mojang.Minecraft
    - sh.ppy.osu